# Generated by Django 2.0.6 on 2018-06-26 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, upload_to='.\\sss'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='DocProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doc', to='test1.Project'),
        ),
    ]
